# Generated by Django 6.0 on 2026-03-14 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vip', models.BooleanField(default=False, verbose_name='是否为VIP会员')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身高(cm)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='体重(kg)')),
                ('style_preference', models.CharField(blank=True, choices=[('minimalist', '极简风'), ('sports', '运动风'), ('business', '商务风'), ('street', '街头风')], max_length=20, null=True, verbose_name='风格偏好')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户详细资料',
                'verbose_name_plural': '用户详细资料',
            },
        ),
    ]
