# Generated by Django 6.0 on 2026-04-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, help_text='用逗号分隔，例如：淡雾紫,海军蓝,暗夜黑', max_length=255, null=True, verbose_name='可选颜色'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='用逗号分隔，例如：S,M,L,XL', max_length=255, null=True, verbose_name='可选尺码'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/detail/', verbose_name='副图')),
                ('color_mark', models.CharField(blank=True, help_text='留空则为通用细节图', max_length=50, null=True, verbose_name='对应颜色标签')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品副图',
                'verbose_name_plural': '商品副图',
            },
        ),
    ]
