# Generated by Django 6.0 on 2026-05-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_address_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('selected_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='选中颜色')),
                ('selected_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='选中尺码')),
                ('is_checked', models.BooleanField(default=True, verbose_name='是否勾选')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车明细',
                'verbose_name_plural': '购物车明细',
            },
        ),
    ]
