# Generated by Django 6.0 on 2026-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='关联的用户ID')),
                ('sender_type', models.CharField(choices=[('user', '用户'), ('admin', '客服')], max_length=10)),
                ('content', models.TextField(help_text='消息内容')),
                ('is_read', models.BooleanField(default=False, help_text='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
