# Generated by Django 6.0 on 2026-05-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/details/', verbose_name='详情图片')),
                ('order', models.IntegerField(default=0, verbose_name='展示顺序(从小到大)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='products.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品详情图',
                'verbose_name_plural': '商品详情图',
                'ordering': ['order'],
            },
        ),
    ]
