# Generated by Django 6.0 on 2026-05-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productdetailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('size', models.CharField(max_length=50, verbose_name='尺码')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '规格库存',
                'verbose_name_plural': '规格库存',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
